// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKgSy1UdRitxL6op9tgf6osrVkykL6Rao',
    appId: '1:809300510546:android:b27b43f92f2933a501dc8b',
    messagingSenderId: '809300510546',
    projectId: 'educastock-136cd',
    storageBucket: 'educastock-136cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYmd7ESC36_wrv8jc7S2sKbYxnQcmfVto',
    appId: '1:809300510546:ios:d1604ebe65a40af401dc8b',
    messagingSenderId: '809300510546',
    projectId: 'educastock-136cd',
    storageBucket: 'educastock-136cd.firebasestorage.app',
    iosBundleId: 'br.org.casadacrianca.educastock',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLqSJp70KsjEfeSU84RlMyAOVLrFL30gw',
    appId: '1:809300510546:web:15809012980a553401dc8b',
    messagingSenderId: '809300510546',
    projectId: 'educastock-136cd',
    authDomain: 'educastock-136cd.firebaseapp.com',
    storageBucket: 'educastock-136cd.firebasestorage.app',
  );

}